/**
 * Parallel Make
 * CS 241 - Fall 2016
 */

#pragma once
/**
 * this file exists so that we can provide a main method which does a variety of
 * handy things.
 *
 * DO NOT EDIT THIS FILE!
 */

// entry point for student code
int parmake(int argc, char **argv);
